### ISSUE TITLE
upgrade sqlx to 0.6

### ISSUE THREAD

**Issue by clouds56** [NyxCode/ormx#32]

**Comment by alercah** [comment]
Any chance this will get done soon? This is a big blocker on upgrading.

**Comment by paramako** [comment]
any updates on this? I'm afraid we'll need to move to another orm as looks like this one is not maintained anymore :(

**Comment by NyxCode** [comment]
Ill publish a new version in the coming days!

**Comment by NyxCode** [comment]
Maintaining an OS project is a lot of work, and I've got plenty of things on my plate right now. However, I don't want to just abandon this, so I'll do my best to keep it in a usable state!

**Comment by k-bx** [comment]
hi @NyxCode , sorry to bug you. https://crates.io/crates/ormx/0.10.0/dependencies is still showing sqlx being `^ 0.5`. any chance of updating?

**Comment by TTWNO** [comment]
This still isn't fixed; the issue should at least be re-opened until a new crate version is published.

@NyxCode , it doesn't look like a new version has been released. Is there anything special that needs to be done to release a new version? I'd certainly be happy to help.

The issue I'm having is I need the `sqlx::test` macro, which was introduced in 0.6, and I'm also depending on `ormx`.

Let me know if you need any help getting the new version up.

**Comment by TTWNO** [comment]
For those who are having issues with compatibility with `sqlx` 0.6, the good news is the updated code can be found in this repository. If you specify `ormx` as a git dependency with this repo's URL, you should be fine.
