### ISSUE TITLE
Unable to install ormx with sqlite

### ISSUE THREAD

**Issue by 3tilley** [NyxCode/ormx#38]
Hello,

I tried to install ormx to use with sqlx and sqlite, it didn't work, it looks like there might be some dependency issues? Failed on Windows and Linux:

`$ cargo new ormx-test && cd ormx-test && cargo add ormx sqlx -F sqlx/sqlite -F ormx/sqlite`

```
error: failed to select a version for the requirement `ahash = "^0.6.2"`
candidate versions found which didn't match: 0.8.6, 0.8.5, 0.8.4, ...
location searched: crates.io index
required by package `sqlx-core v0.5.1`
    ... which satisfies dependency `sqlx-core = "^0.5.1"` of package `sqlx v0.5.1`
    ... which satisfies dependency `sqlx = "^0.5"` of package `ormx v0.10.0`
    ... which satisfies dependency `ormx = "^0.10.0"` of package `ormx-test v0.1.0 (/home/max/git/ormx-test)`
perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by mclrc** [comment]
I know I'm very late, but I think you just can't use the latest sqlx version. Using sqlx 0.6.0 works for me.

**Comment by NyxCode** [comment]
Sorry for not responding sooner.  
sqlite is currently not supported. I don't think it would take a lot of effort, but I have absolutely no usecase for it at the moment.
