### ISSUE TITLE
Discussion: Additional features, road towards a full-fledged ORM

### ISSUE THREAD

**Issue by OtaK** [NyxCode/ormx#8]
Hey, 

I've been thinking a lot about that stuff lately and I honestly think ormx is the perfect candidate to build on and iterate towards a full-fledged ORM.

The features I'd personally like to see are more or less the featureset of [Sequelize](https://sequelize.org/master/), to be more accurate: 

1. Schema definition & synchronization
2. Migrations [done on sqlx side]
3. Free queries with convenience methods (see [Sequelize Model Finders](https://sequelize.org/master/manual/model-querying-finders.html))

Number 3 would be pretty much just additional things to implement on `Table` and would be the most trivial
Number 1 is a tough one, as we need to find a way to synchronize tables *before* sqlx compiles and checks our queries.

For instance on an empty database, a model would try to compile its queries, *but* the table doesn't exist yet so compilation would fail.

I'm currently experimenting here: https://github.com/OtaK/ormx/tree/otak/schema-sync

**Comment by NyxCode** [comment]
@NyxCode did you make any progress on this? How did your experiments go? Really curious!

**Comment by NyxCode** [comment]
Closing this for now due to inactivity. I would happily reopen this though!
